import 'package:flutter/material.dart';

class CategoryIcons {
  CategoryIcons._();

  static const Map<String, IconData> icons = {
    // ==================== FOOD & DRINKS ====================
    'restaurant': Icons.restaurant,
    'restaurant_menu': Icons.restaurant_menu,
    'fastfood': Icons.fastfood,
    'local_pizza': Icons.local_pizza,
    'bakery_dining': Icons.bakery_dining,
    'ramen_dining': Icons.ramen_dining,
    'lunch_dining': Icons.lunch_dining,
    'dinner_dining': Icons.dinner_dining,
    'brunch_dining': Icons.brunch_dining,
    'breakfast_dining': Icons.breakfast_dining,
    'set_meal': Icons.set_meal,
    'rice_bowl': Icons.rice_bowl,
    'icecream': Icons.icecream,
    'cake': Icons.cake,
    'coffee': Icons.coffee,
    'local_cafe': Icons.local_cafe,
    'local_bar': Icons.local_bar,
    'wine_bar': Icons.wine_bar,
    'sports_bar': Icons.sports_bar,
    'liquor': Icons.liquor,
    'local_drink': Icons.local_drink,
    'emoji_food_beverage': Icons.emoji_food_beverage,
    'takeout_dining': Icons.takeout_dining,
    'delivery_dining': Icons.delivery_dining,
    'tapas': Icons.tapas,
    'kitchen': Icons.kitchen,
    'cookie': Icons.cookie,

    // ==================== SHOPPING ====================
    'shopping_cart': Icons.shopping_cart,
    'shopping_bag': Icons.shopping_bag,
    'shopping_basket': Icons.shopping_basket,
    'local_grocery_store': Icons.local_grocery_store,
    'local_mall': Icons.local_mall,
    'storefront': Icons.storefront,
    'store': Icons.store,
    'checkroom': Icons.checkroom,
    'dry_cleaning': Icons.dry_cleaning,
    'iron': Icons.iron,
    'wallet': Icons.wallet,
    'redeem': Icons.redeem,
    'sell': Icons.sell,
    'local_offer': Icons.local_offer,
    'loyalty': Icons.loyalty,
    'diamond': Icons.diamond,

    // ==================== TRANSPORTATION ====================
    'directions_car': Icons.directions_car,
    'directions_bus': Icons.directions_bus,
    'directions_railway': Icons.directions_railway,
    'directions_subway': Icons.directions_subway,
    'directions_bike': Icons.directions_bike,
    'directions_walk': Icons.directions_walk,
    'directions_boat': Icons.directions_boat,
    'commute': Icons.commute,
    'flight': Icons.flight,
    'flight_takeoff': Icons.flight_takeoff,
    'flight_land': Icons.flight_land,
    'local_taxi': Icons.local_taxi,
    'local_gas_station': Icons.local_gas_station,
    'ev_station': Icons.ev_station,
    'local_parking': Icons.local_parking,
    'two_wheeler': Icons.two_wheeler,
    'electric_bike': Icons.electric_bike,
    'electric_car': Icons.electric_car,
    'electric_scooter': Icons.electric_scooter,
    'pedal_bike': Icons.pedal_bike,
    'motorcycle': Icons.motorcycle,
    'train': Icons.train,
    'tram': Icons.tram,
    'airport_shuttle': Icons.airport_shuttle,
    'car_rental': Icons.car_rental,
    'car_repair': Icons.car_repair,
    'tire_repair': Icons.tire_repair,
    'sailing': Icons.sailing,
    'houseboat': Icons.houseboat,

    // ==================== HOME & UTILITIES ====================
    'home': Icons.home,
    'house': Icons.house,
    'cottage': Icons.cottage,
    'apartment': Icons.apartment,
    'villa': Icons.villa,
    'bungalow': Icons.bungalow,
    'cabin': Icons.cabin,
    'bed': Icons.bed,
    'bedroom_parent': Icons.bedroom_parent,
    'bathroom': Icons.bathroom,
    'bathtub': Icons.bathtub,
    'shower': Icons.shower,
    'living': Icons.living,
    'chair': Icons.chair,
    'table_restaurant': Icons.table_restaurant,
    'weekend': Icons.weekend,
    'door_sliding': Icons.door_sliding,
    'window': Icons.window,
    'lightbulb': Icons.lightbulb,
    'power': Icons.power,
    'electrical_services': Icons.electrical_services,
    'water_drop': Icons.water_drop,
    'hot_tub': Icons.hot_tub,
    'microwave': Icons.microwave,
    'blender': Icons.blender,
    'countertops': Icons.countertops,
    'phone': Icons.phone,
    'wifi': Icons.wifi,
    'router': Icons.router,
    'tv': Icons.tv,
    'connected_tv': Icons.connected_tv,
    'air': Icons.air,
    'ac_unit': Icons.ac_unit,
    'thermostat': Icons.thermostat,
    'cleaning_services': Icons.cleaning_services,
    'plumbing': Icons.plumbing,
    'handyman': Icons.handyman,
    'construction': Icons.construction,
    'roofing': Icons.roofing,
    'foundation': Icons.foundation,
    'format_paint': Icons.format_paint,
    'grass': Icons.grass,
    'yard': Icons.yard,
    'fence': Icons.fence,
    'outdoor_grill': Icons.outdoor_grill,
    'deck': Icons.deck,
    'umbrella': Icons.umbrella,

    // ==================== HEALTH & FITNESS ====================
    'medical_services': Icons.medical_services,
    'local_hospital': Icons.local_hospital,
    'local_pharmacy': Icons.local_pharmacy,
    'medication': Icons.medication,
    'medication_liquid': Icons.medication_liquid,
    'vaccines': Icons.vaccines,
    'healing': Icons.healing,
    'health_and_safety': Icons.health_and_safety,
    'monitor_heart': Icons.monitor_heart,
    'favorite': Icons.favorite,
    'favorite_border': Icons.favorite_border,
    'psychology': Icons.psychology,
    'self_improvement': Icons.self_improvement,
    'fitness_center': Icons.fitness_center,
    'sports_gymnastics': Icons.sports_gymnastics,
    'sports_martial_arts': Icons.sports_martial_arts,
    'directions_run': Icons.directions_run,
    'hiking': Icons.hiking,
    'nordic_walking': Icons.nordic_walking,
    'spa': Icons.spa,
    'hot_tub_alt': Icons.hot_tub,
    'face_retouching_natural': Icons.face_retouching_natural,
    'face': Icons.face,
    'masks': Icons.masks,
    'accessibility': Icons.accessibility,
    'blind': Icons.blind,
    'elderly': Icons.elderly,
    'pregnant_woman': Icons.pregnant_woman,
    'stroller': Icons.stroller,

    // ==================== EDUCATION ====================
    'school': Icons.school,
    'cast_for_education': Icons.cast_for_education,
    'menu_book': Icons.menu_book,
    'auto_stories': Icons.auto_stories,
    'book': Icons.book,
    'library_books': Icons.library_books,
    'import_contacts': Icons.import_contacts,
    'chrome_reader_mode': Icons.chrome_reader_mode,
    'article': Icons.article,
    'newspaper': Icons.newspaper,
    'history_edu': Icons.history_edu,
    'science': Icons.science,
    'biotech': Icons.biotech,
    'calculate': Icons.calculate,
    'architecture': Icons.architecture,
    'draw': Icons.draw,
    'edit': Icons.edit,
    'create': Icons.create,
    'design_services': Icons.design_services,
    'translate': Icons.translate,
    'language': Icons.language,
    'abc': Icons.abc,
    'school_alt': Icons.school,
    'class_': Icons.class_,
    'backpack': Icons.backpack,
    'workspace_premium': Icons.workspace_premium,

    // ==================== ENTERTAINMENT ====================
    'movie': Icons.movie,
    'movie_filter': Icons.movie_filter,
    'theaters': Icons.theaters,
    'live_tv': Icons.live_tv,
    'music_note': Icons.music_note,
    'library_music': Icons.library_music,
    'headphones': Icons.headphones,
    'headset': Icons.headset,
    'speaker': Icons.speaker,
    'piano': Icons.piano,
    'sports_esports': Icons.sports_esports,
    'videogame_asset': Icons.videogame_asset,
    'casino': Icons.casino,
    'attractions': Icons.attractions,
    'roller_skating': Icons.roller_skating,
    'skateboarding': Icons.skateboarding,
    'snowboarding': Icons.snowboarding,
    'sledding': Icons.sledding,
    'paragliding': Icons.paragliding,
    'kitesurfing': Icons.kitesurfing,
    'surfing': Icons.surfing,
    'scuba_diving': Icons.scuba_diving,
    'downhill_skiing': Icons.downhill_skiing,
    'snowshoeing': Icons.snowshoeing,
    'ice_skating': Icons.ice_skating,
    'sports': Icons.sports,
    'sports_soccer': Icons.sports_soccer,
    'sports_basketball': Icons.sports_basketball,
    'sports_baseball': Icons.sports_baseball,
    'sports_tennis': Icons.sports_tennis,
    'sports_volleyball': Icons.sports_volleyball,
    'sports_football': Icons.sports_football,
    'sports_hockey': Icons.sports_hockey,
    'sports_golf': Icons.sports_golf,
    'sports_cricket': Icons.sports_cricket,
    'sports_rugby': Icons.sports_rugby,
    'sports_mma': Icons.sports_mma,
    'sports_kabaddi': Icons.sports_kabaddi,
    'sports_handball': Icons.sports_handball,
    'pool': Icons.pool,
    'golf_course': Icons.golf_course,
    'sports_score': Icons.sports_score,
    'emoji_events': Icons.emoji_events,
    'celebration': Icons.celebration,
    'party_mode': Icons.party_mode,
    'nightlife': Icons.nightlife,
    'festival': Icons.festival,

    // ==================== TRAVEL & VACATION ====================
    'luggage': Icons.luggage,
    'backpack_travel': Icons.backpack,
    'local_airport': Icons.local_airport,
    'hotel': Icons.hotel,
    'holiday_village': Icons.holiday_village,
    'beach_access': Icons.beach_access,
    'park': Icons.park,
    'forest': Icons.forest,
    'landscape': Icons.landscape,
    'terrain': Icons.terrain,
    'photo_camera': Icons.photo_camera,
    'camera_alt': Icons.camera_alt,
    'photo': Icons.photo,
    'panorama': Icons.panorama,
    'map': Icons.map,
    'explore': Icons.explore,
    'tour': Icons.tour,
    'museum': Icons.museum,
    'church': Icons.church,
    'temple_buddhist': Icons.temple_buddhist,
    'temple_hindu': Icons.temple_hindu,
    'mosque': Icons.mosque,
    'synagogue': Icons.synagogue,
    'castle': Icons.castle,
    'fort': Icons.fort,
    'stadium': Icons.stadium,
    'local_activity': Icons.local_activity,
    'local_movies': Icons.local_movies,
    'local_play': Icons.local_play,
    'local_see': Icons.local_see,
    'local_library': Icons.local_library,
    'local_convenience_store': Icons.local_convenience_store,
    'local_atm': Icons.local_atm,
    'local_laundry_service': Icons.local_laundry_service,
    'local_car_wash': Icons.local_car_wash,
    'local_florist': Icons.local_florist,
    'local_fire_department': Icons.local_fire_department,
    'local_police': Icons.local_police,
    'local_post_office': Icons.local_post_office,
    'local_printshop': Icons.local_printshop,
    'compass_calibration': Icons.compass_calibration,
    'flag': Icons.flag,
    'public': Icons.public,

    // ==================== TECHNOLOGY ====================
    'devices': Icons.devices,
    'computer': Icons.computer,
    'laptop': Icons.laptop,
    'laptop_mac': Icons.laptop_mac,
    'laptop_chromebook': Icons.laptop_chromebook,
    'desktop_mac': Icons.desktop_mac,
    'desktop_windows': Icons.desktop_windows,
    'tablet': Icons.tablet,
    'tablet_mac': Icons.tablet_mac,
    'tablet_android': Icons.tablet_android,
    'phone_android': Icons.phone_android,
    'phone_iphone': Icons.phone_iphone,
    'smartphone': Icons.smartphone,
    'watch': Icons.watch,
    'smart_display': Icons.smart_display,
    'smart_screen': Icons.smart_screen,
    'smart_toy': Icons.smart_toy,
    'videocam': Icons.videocam,
    'camera': Icons.camera,
    'photo_camera_front': Icons.photo_camera_front,
    'photo_camera_back': Icons.photo_camera_back,
    'memory': Icons.memory,
    'storage': Icons.storage,
    'sd_storage': Icons.sd_storage,
    'usb': Icons.usb,
    'keyboard': Icons.keyboard,
    'mouse': Icons.mouse,
    'monitor': Icons.monitor,
    'print': Icons.print,
    'scanner': Icons.scanner,
    'videogame_asset_off': Icons.videogame_asset_off,
    'sim_card': Icons.sim_card,
    'battery_charging_full': Icons.battery_charging_full,
    'cable': Icons.cable,
    'developer_board': Icons.developer_board,
    'dns': Icons.dns,
    'cloud': Icons.cloud,
    'cloud_upload': Icons.cloud_upload,
    'cloud_download': Icons.cloud_download,
    'settings': Icons.settings,
    'build': Icons.build,
    'code': Icons.code,
    'terminal': Icons.terminal,
    'bug_report': Icons.bug_report,
    'apps': Icons.apps,

    // ==================== PETS & ANIMALS ====================
    'pets': Icons.pets,
    'cruelty_free': Icons.cruelty_free,

    // ==================== FAMILY & KIDS ====================
    'child_care': Icons.child_care,
    'child_friendly': Icons.child_friendly,
    'family_restroom': Icons.family_restroom,
    'baby_changing_station': Icons.baby_changing_station,
    'toys': Icons.toys,
    'smart_toy_alt': Icons.smart_toy,
    'cake_alt': Icons.cake,
    'redeem_alt': Icons.redeem,
    'card_giftcard': Icons.card_giftcard,

    // ==================== WORK & BUSINESS ====================
    'work': Icons.work,
    'work_outline': Icons.work_outline,
    'work_history': Icons.work_history,
    'business': Icons.business,
    'business_center': Icons.business_center,
    'corporate_fare': Icons.corporate_fare,
    'storefront_alt': Icons.storefront,
    'point_of_sale': Icons.point_of_sale,
    'receipt': Icons.receipt,
    'receipt_long': Icons.receipt_long,
    'request_quote': Icons.request_quote,
    'description': Icons.description,
    'assignment': Icons.assignment,
    'assignment_ind': Icons.assignment_ind,
    'badge': Icons.badge,
    'contact_mail': Icons.contact_mail,
    'contact_phone': Icons.contact_phone,
    'contacts': Icons.contacts,
    'perm_contact_calendar': Icons.perm_contact_calendar,
    'people': Icons.people,
    'people_alt': Icons.people_alt,
    'groups': Icons.groups,
    'group_work': Icons.group_work,
    'handshake': Icons.handshake,
    'meeting_room': Icons.meeting_room,
    'event': Icons.event,
    'event_available': Icons.event_available,
    'calendar_today': Icons.calendar_today,
    'calendar_month': Icons.calendar_month,
    'today': Icons.today,
    'schedule': Icons.schedule,
    'access_time': Icons.access_time,
    'alarm': Icons.alarm,
    'pending_actions': Icons.pending_actions,
    'task': Icons.task,
    'task_alt': Icons.task_alt,
    'checklist': Icons.checklist,
    'fact_check': Icons.fact_check,
    'rule': Icons.rule,
    'gavel': Icons.gavel,
    'policy': Icons.policy,
    'verified': Icons.verified,
    'workspace_verified': Icons.workspace_premium,
    'approval': Icons.approval,

    // ==================== INCOME & MONEY ====================
    'payments': Icons.payments,
    'payment': Icons.payment,
    'trending_up': Icons.trending_up,
    'trending_down': Icons.trending_down,
    'attach_money': Icons.attach_money,
    'money': Icons.money,
    'money_off': Icons.money_off,
    'local_atm_alt': Icons.local_atm,
    'currency_exchange': Icons.currency_exchange,
    'account_balance': Icons.account_balance,
    'account_balance_wallet': Icons.account_balance_wallet,
    'savings': Icons.savings,
    'monetization_on': Icons.monetization_on,
    'price_check': Icons.price_check,
    'price_change': Icons.price_change,
    'credit_card': Icons.credit_card,
    'credit_card_off': Icons.credit_card_off,
    'credit_score': Icons.credit_score,
    'atm': Icons.atm,
    'euro': Icons.euro,
    'currency_pound': Icons.currency_pound,
    'currency_yen': Icons.currency_yen,
    'currency_yuan': Icons.currency_yuan,
    'currency_rupee': Icons.currency_rupee,
    'currency_ruble': Icons.currency_ruble,
    'currency_lira': Icons.currency_lira,
    'currency_franc': Icons.currency_franc,
    'currency_bitcoin': Icons.currency_bitcoin,
    'real_estate_agent': Icons.real_estate_agent,
    'sell_alt': Icons.sell,
    'paid': Icons.paid,
    'calculate_alt': Icons.calculate,
    'assessment': Icons.assessment,
    'analytics': Icons.analytics,
    'insights': Icons.insights,
    'pie_chart': Icons.pie_chart,
    'bar_chart': Icons.bar_chart,
    'show_chart': Icons.show_chart,
    'timeline': Icons.timeline,
    'leaderboard': Icons.leaderboard,
    'stacked_line_chart': Icons.stacked_line_chart,
    'ssid_chart': Icons.ssid_chart,
    'waterfall_chart': Icons.waterfall_chart,
    'addchart': Icons.addchart,
    'insert_chart': Icons.insert_chart,

    // ==================== SECURITY ====================
    'security': Icons.security,
    'shield': Icons.shield,
    'admin_panel_settings': Icons.admin_panel_settings,
    'lock': Icons.lock,
    'lock_open': Icons.lock_open,
    'vpn_key': Icons.vpn_key,
    'key': Icons.key,
    'password': Icons.password,
    'fingerprint': Icons.fingerprint,
    'face_unlock_sharp': Icons.face_unlock_sharp,

    // ==================== NATURE & ENVIRONMENT ====================
    'nature': Icons.nature,
    'nature_people': Icons.nature_people,
    'park_alt': Icons.park,
    'forest_alt': Icons.forest,
    'eco': Icons.eco,
    'energy_savings_leaf': Icons.energy_savings_leaf,
    'compost': Icons.compost,
    'recycling': Icons.recycling,
    'delete_sweep': Icons.delete_sweep,
    'water': Icons.water,
    'waves': Icons.waves,
    'wb_sunny': Icons.wb_sunny,
    'light_mode': Icons.light_mode,
    'dark_mode': Icons.dark_mode,
    'nights_stay': Icons.nights_stay,
    'cloud_alt': Icons.cloud,
    'thunderstorm': Icons.thunderstorm,
    'rainy': Icons.grain,
    'snowy': Icons.ac_unit,
    'sunny_snowing': Icons.sunny_snowing,
    'rainbow': Icons.looks,
    'volcano': Icons.volcano,

    // ==================== COMMUNICATION ====================
    'email': Icons.email,
    'mail': Icons.mail,
    'send': Icons.send,
    'message': Icons.message,
    'chat': Icons.chat,
    'chat_bubble': Icons.chat_bubble,
    'forum': Icons.forum,
    'comment': Icons.comment,
    'textsms': Icons.textsms,
    'call': Icons.call,
    'phone_in_talk': Icons.phone_in_talk,
    'video_call': Icons.video_call,
    'duo': Icons.duo,
    'notifications': Icons.notifications,
    'notifications_active': Icons.notifications_active,
    'campaign': Icons.campaign,
    'announcement': Icons.announcement,
    'rss_feed': Icons.rss_feed,
    'share': Icons.share,
    'ios_share': Icons.ios_share,
    'qr_code': Icons.qr_code,
    'qr_code_scanner': Icons.qr_code_scanner,

    // ==================== GENERAL / MISC ====================
    'category': Icons.category,
    'label': Icons.label,
    'label_important': Icons.label_important,
    'folder': Icons.folder,
    'folder_open': Icons.folder_open,
    'folder_special': Icons.folder_special,
    'star': Icons.star,
    'star_border': Icons.star_border,
    'star_half': Icons.star_half,
    'grade': Icons.grade,
    'thumb_up': Icons.thumb_up,
    'thumb_down': Icons.thumb_down,
    'sentiment_satisfied': Icons.sentiment_satisfied,
    'sentiment_dissatisfied': Icons.sentiment_dissatisfied,
    'mood': Icons.mood,
    'emoji_emotions': Icons.emoji_emotions,
    'emoji_objects': Icons.emoji_objects,
    'emoji_symbols': Icons.emoji_symbols,
    'emoji_nature': Icons.emoji_nature,
    'emoji_transportation': Icons.emoji_transportation,
    'emoji_flags': Icons.emoji_flags,
    'emoji_people': Icons.emoji_people,
    'add': Icons.add,
    'add_circle': Icons.add_circle,
    'remove': Icons.remove,
    'remove_circle': Icons.remove_circle,
    'edit_alt': Icons.edit,
    'delete': Icons.delete,
    'delete_forever': Icons.delete_forever,
    'restore': Icons.restore,
    'refresh': Icons.refresh,
    'sync': Icons.sync,
    'update': Icons.update,
    'autorenew': Icons.autorenew,
    'loop': Icons.loop,
    'done': Icons.done,
    'done_all': Icons.done_all,
    'check': Icons.check,
    'check_circle': Icons.check_circle,
    'cancel': Icons.cancel,
    'close': Icons.close,
    'block': Icons.block,
    'error': Icons.error,
    'warning': Icons.warning,
    'info': Icons.info,
    'help': Icons.help,
    'question_mark': Icons.question_mark,
    'priority_high': Icons.priority_high,
    'new_releases': Icons.new_releases,
    'bolt': Icons.bolt,
    'flash_on': Icons.flash_on,
    'highlight': Icons.highlight,
    'brightness_high': Icons.brightness_high,
    'brightness_low': Icons.brightness_low,
    'contrast': Icons.contrast,
    'palette': Icons.palette,
    'color_lens': Icons.color_lens,
    'brush': Icons.brush,
    'format_color_fill': Icons.format_color_fill,
    'format_color_text': Icons.format_color_text,
    'more_horiz': Icons.more_horiz,
    'more_vert': Icons.more_vert,
    'drag_indicator': Icons.drag_indicator,
    'list': Icons.list,
    'view_list': Icons.view_list,
    'view_module': Icons.view_module,
    'grid_view': Icons.grid_view,
    'dashboard': Icons.dashboard,
    'widgets': Icons.widgets,
    'extension': Icons.extension,
    'puzzle': Icons.extension,
    'interests': Icons.interests,
    'whatshot': Icons.whatshot,
    'flare': Icons.flare,
    'auto_awesome': Icons.auto_awesome,
    'auto_fix_high': Icons.auto_fix_high,
    'lens_blur': Icons.lens_blur,
    'blur_on': Icons.blur_on,
    'texture': Icons.texture,
    'grain': Icons.grain,
    'opacity': Icons.opacity,
    'transform': Icons.transform,
    'animation': Icons.animation,
    'motion_photos_on': Icons.motion_photos_on,
    'slow_motion_video': Icons.slow_motion_video,
    'speed': Icons.speed,
    'rocket': Icons.rocket,
    'rocket_launch': Icons.rocket_launch,
    'science_alt': Icons.science,
    'psychology_alt': Icons.psychology_alt,
    'diversity_1': Icons.diversity_1,
    'diversity_2': Icons.diversity_2,
    'diversity_3': Icons.diversity_3,
    'volunteer_activism': Icons.volunteer_activism,
    'handshake_alt': Icons.handshake,
    'waving_hand': Icons.waving_hand,
    'front_hand': Icons.front_hand,
    'back_hand': Icons.back_hand,
    'pan_tool': Icons.pan_tool,
    'thumb_up_alt': Icons.thumb_up_alt,
    'thumb_down_alt': Icons.thumb_down_alt,
    'sign_language': Icons.sign_language,
    'heart_broken': Icons.heart_broken,
    'hive': Icons.hive,
    'hexagon': Icons.hexagon,
    'pentagon': Icons.pentagon,
    'square': Icons.square,
    'circle': Icons.circle,
    'rectangle': Icons.rectangle,
    'change_history': Icons.change_history,
    'trip_origin': Icons.trip_origin,
    'lens': Icons.lens,
    'panorama_fish_eye': Icons.panorama_fish_eye,
    'radio_button_unchecked': Icons.radio_button_unchecked,
    'radio_button_checked': Icons.radio_button_checked,
    'adjust': Icons.adjust,
    'brightness_1': Icons.brightness_1,
    'brightness_2': Icons.brightness_2,
    'brightness_3': Icons.brightness_3,
    'brightness_4': Icons.brightness_4,
    'brightness_5': Icons.brightness_5,
    'brightness_6': Icons.brightness_6,
    'brightness_7': Icons.brightness_7,
  };

  static IconData getIcon(String? code) {
    if (code == null || code.isEmpty) {
      return Icons.category;
    }
    return icons[code] ?? Icons.category;
  }

  static List<String> get allIconCodes => icons.keys.toList();

  /// Grouped icons by category for better UI selection
  static const Map<String, List<String>> iconGroups = {
    '🍔 Food & Drinks': [
      'restaurant', 'restaurant_menu', 'fastfood', 'local_pizza', 'bakery_dining',
      'ramen_dining', 'lunch_dining', 'dinner_dining', 'brunch_dining', 'breakfast_dining',
      'set_meal', 'rice_bowl', 'icecream', 'cake', 'coffee', 'local_cafe', 'local_bar',
      'wine_bar', 'sports_bar', 'liquor', 'local_drink', 'emoji_food_beverage',
      'takeout_dining', 'delivery_dining', 'tapas', 'kitchen', 'cookie',
    ],
    '🛒 Shopping': [
      'shopping_cart', 'shopping_bag', 'shopping_basket', 'local_grocery_store',
      'local_mall', 'storefront', 'store', 'checkroom', 'dry_cleaning', 'iron',
      'wallet', 'redeem', 'sell', 'local_offer', 'loyalty', 'diamond',
    ],
    '🚗 Transportation': [
      'directions_car', 'directions_bus', 'directions_railway', 'directions_subway',
      'directions_bike', 'directions_walk', 'directions_boat', 'commute', 'flight',
      'flight_takeoff', 'flight_land', 'local_taxi', 'local_gas_station', 'ev_station',
      'local_parking', 'two_wheeler', 'electric_bike', 'electric_car', 'electric_scooter',
      'pedal_bike', 'motorcycle', 'train', 'tram', 'airport_shuttle', 'car_rental',
      'car_repair', 'tire_repair', 'sailing', 'houseboat',
    ],
    '🏠 Home & Utilities': [
      'home', 'house', 'cottage', 'apartment', 'villa', 'bungalow', 'cabin',
      'bed', 'bedroom_parent', 'bathroom', 'bathtub', 'shower', 'living', 'chair',
      'table_restaurant', 'weekend', 'door_sliding', 'window', 'lightbulb', 'power',
      'electrical_services', 'water_drop', 'hot_tub', 'microwave', 'blender',
      'countertops', 'phone', 'wifi', 'router', 'tv', 'connected_tv', 'air',
      'ac_unit', 'thermostat', 'cleaning_services', 'plumbing', 'handyman',
      'construction', 'roofing', 'foundation', 'format_paint', 'grass', 'yard',
      'fence', 'outdoor_grill', 'deck', 'umbrella',
    ],
    '🏥 Health & Fitness': [
      'medical_services', 'local_hospital', 'local_pharmacy', 'medication',
      'medication_liquid', 'vaccines', 'healing', 'health_and_safety', 'monitor_heart',
      'favorite', 'favorite_border', 'psychology', 'self_improvement', 'fitness_center',
      'sports_gymnastics', 'sports_martial_arts', 'directions_run', 'hiking',
      'nordic_walking', 'spa', 'face_retouching_natural', 'face', 'masks',
      'accessibility', 'blind', 'elderly', 'pregnant_woman', 'stroller',
    ],
    '📚 Education': [
      'school', 'cast_for_education', 'menu_book', 'auto_stories', 'book',
      'library_books', 'import_contacts', 'chrome_reader_mode', 'article', 'newspaper',
      'history_edu', 'science', 'biotech', 'calculate', 'architecture', 'draw',
      'edit', 'create', 'design_services', 'translate', 'language', 'abc',
      'class_', 'backpack', 'workspace_premium',
    ],
    '🎬 Entertainment': [
      'movie', 'movie_filter', 'theaters', 'live_tv', 'music_note', 'library_music',
      'headphones', 'headset', 'speaker', 'piano', 'sports_esports', 'videogame_asset',
      'casino', 'attractions', 'roller_skating', 'skateboarding', 'snowboarding',
      'sledding', 'paragliding', 'kitesurfing', 'surfing', 'scuba_diving',
      'downhill_skiing', 'snowshoeing', 'ice_skating', 'sports', 'sports_soccer',
      'sports_basketball', 'sports_baseball', 'sports_tennis', 'sports_volleyball',
      'sports_football', 'sports_hockey', 'sports_golf', 'sports_cricket',
      'sports_rugby', 'sports_mma', 'sports_kabaddi', 'sports_handball', 'pool',
      'golf_course', 'sports_score', 'emoji_events', 'celebration', 'party_mode',
      'nightlife', 'festival',
    ],
    '✈️ Travel & Vacation': [
      'luggage', 'local_airport', 'hotel', 'holiday_village', 'beach_access',
      'park', 'forest', 'landscape', 'terrain', 'photo_camera', 'camera_alt',
      'photo', 'panorama', 'map', 'explore', 'tour', 'museum', 'church',
      'temple_buddhist', 'temple_hindu', 'mosque', 'synagogue', 'castle', 'fort',
      'stadium', 'local_activity', 'local_movies', 'local_play', 'local_see',
      'local_library', 'local_convenience_store', 'local_atm', 'local_laundry_service',
      'local_car_wash', 'local_florist', 'local_fire_department', 'local_police',
      'local_post_office', 'local_printshop', 'compass_calibration', 'flag', 'public',
    ],
    '💻 Technology': [
      'devices', 'computer', 'laptop', 'laptop_mac', 'laptop_chromebook',
      'desktop_mac', 'desktop_windows', 'tablet', 'tablet_mac', 'tablet_android',
      'phone_android', 'phone_iphone', 'smartphone', 'watch', 'smart_display',
      'smart_screen', 'smart_toy', 'videocam', 'camera', 'photo_camera_front',
      'photo_camera_back', 'memory', 'storage', 'sd_storage', 'usb', 'keyboard',
      'mouse', 'monitor', 'print', 'scanner', 'videogame_asset_off', 'sim_card',
      'battery_charging_full', 'cable', 'developer_board', 'dns', 'cloud',
      'cloud_upload', 'cloud_download', 'settings', 'build', 'code', 'terminal',
      'bug_report', 'apps',
    ],
    '👶 Family & Kids': [
      'child_care', 'child_friendly', 'family_restroom', 'baby_changing_station',
      'toys', 'pets', 'cruelty_free', 'card_giftcard',
    ],
    '💼 Work & Business': [
      'work', 'work_outline', 'work_history', 'business', 'business_center',
      'corporate_fare', 'point_of_sale', 'receipt', 'receipt_long', 'request_quote',
      'description', 'assignment', 'assignment_ind', 'badge', 'contact_mail',
      'contact_phone', 'contacts', 'perm_contact_calendar', 'people', 'people_alt',
      'groups', 'group_work', 'handshake', 'meeting_room', 'event', 'event_available',
      'calendar_today', 'calendar_month', 'today', 'schedule', 'access_time',
      'alarm', 'pending_actions', 'task', 'task_alt', 'checklist', 'fact_check',
      'rule', 'gavel', 'policy', 'verified', 'approval',
    ],
    '💰 Money & Finance': [
      'payments', 'payment', 'trending_up', 'trending_down', 'attach_money',
      'money', 'money_off', 'currency_exchange', 'account_balance',
      'account_balance_wallet', 'savings', 'monetization_on', 'price_check',
      'price_change', 'credit_card', 'credit_card_off', 'credit_score', 'atm',
      'euro', 'currency_pound', 'currency_yen', 'currency_yuan', 'currency_rupee',
      'currency_ruble', 'currency_lira', 'currency_franc', 'currency_bitcoin',
      'real_estate_agent', 'paid', 'assessment', 'analytics', 'insights',
      'pie_chart', 'bar_chart', 'show_chart', 'timeline', 'leaderboard',
      'stacked_line_chart', 'ssid_chart', 'waterfall_chart', 'addchart', 'insert_chart',
    ],
    '🔒 Security': [
      'security', 'shield', 'admin_panel_settings', 'lock', 'lock_open',
      'vpn_key', 'key', 'password', 'fingerprint', 'face_unlock_sharp',
    ],
    '🌿 Nature': [
      'nature', 'nature_people', 'eco', 'energy_savings_leaf', 'compost',
      'recycling', 'delete_sweep', 'water', 'waves', 'wb_sunny', 'light_mode',
      'dark_mode', 'nights_stay', 'thunderstorm', 'sunny_snowing', 'volcano',
    ],
    '💬 Communication': [
      'email', 'mail', 'send', 'message', 'chat', 'chat_bubble', 'forum',
      'comment', 'textsms', 'call', 'phone_in_talk', 'video_call', 'duo',
      'notifications', 'notifications_active', 'campaign', 'announcement',
      'rss_feed', 'share', 'ios_share', 'qr_code', 'qr_code_scanner',
    ],
    '⭐ General': [
      'category', 'label', 'label_important', 'folder', 'folder_open',
      'folder_special', 'star', 'star_border', 'star_half', 'grade',
      'thumb_up', 'thumb_down', 'sentiment_satisfied', 'sentiment_dissatisfied',
      'mood', 'emoji_emotions', 'emoji_objects', 'emoji_symbols', 'emoji_nature',
      'emoji_transportation', 'emoji_flags', 'emoji_people', 'add', 'add_circle',
      'remove', 'remove_circle', 'delete', 'delete_forever', 'restore', 'refresh',
      'sync', 'update', 'autorenew', 'loop', 'done', 'done_all', 'check',
      'check_circle', 'cancel', 'close', 'block', 'error', 'warning', 'info',
      'help', 'question_mark', 'priority_high', 'new_releases', 'bolt', 'flash_on',
      'highlight', 'more_horiz', 'more_vert', 'dashboard', 'widgets', 'extension',
      'interests', 'whatshot', 'auto_awesome', 'rocket', 'rocket_launch',
      'volunteer_activism', 'waving_hand', 'heart_broken', 'hexagon', 'circle',
    ],
  };

  /// Get list of group names
  static List<String> get groupNames => iconGroups.keys.toList();
}
